<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'WOaUu+eVpee9kQ==');
$cfg_Cs[2]=array(1,1,1,'56We5q2m');
$cfg_Cs[3]=array(2,1,1,'5pS755Wl');
$cfg_Cs[4]=array(0,1,1,'ZeWVhuacjQ==');
$cfg_Cs[5]=array(4,1,1,'5b6u5ZWG');
$cfg_Cs[6]=array(5,1,1,'5b6u5L+h6JCl6ZSA');
$cfg_Cs[7]=array(1,1,1,'5YiA5aGU5Lyg5aWH');
$cfg_Cs[8]=array(7,1,1,'5pS755Wl');
$cfg_Cs[9]=array(5,1,1,'5b6u5reY6JCl6ZSA');
$cfg_Cs[10]=array(0,1,1,'WOijheS/rue9kQ==');
$cfg_Cs[11]=array(10,1,1,'5a6k5YaF6KOF6aWw');
$cfg_Cs[13]=array(4,1,1,'5Lq65omN5oub6IGY');
$cfg_Cs[14]=array(13,1,1,'5YW86IGM5oyH5Y2X');
?>