<?php
$z[0]=Array("pubdate","  \r\n\$a=\"new\"; \r\n\$b=\"\";    \r\n\$c=strftime(\"%d\",\"@me\");\r\n\$d=date(d); \r\nif(\$c==\$d) @me = \$a;  \r\nelse @me = \$b;  \r\n",13,167);
$z[0][4]['runphp']="yes";
$z[1]=Array("pubdate","  \r\n      \$a=\"日\"; \r\n      \$b=\"今日\";    \r\n      \$c=strftime(\"%Y%m%d\",\"@me\");\r\n      \$d=date(Ymd); \r\n      \$e=strftime(\"%d\",\"@me\");\r\n      if(\$c==\$d) @me = \$b;  \r\n      else @me = \$e.\$a;  \r\n      ",204,447);
$z[1][4]['runphp']="yes";
$z[2]=Array("fulltitle","",484,502);
$z[3]=Array("arcurl","",526,541);
$z[4]=Array("shorttitle","",543,562);

?>