<?php
$z[0]=Array("global","",81,108);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("field","",108,136);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",138,167);
$z[2][4]['name']="typename";
$z[3]=Array("global","",222,249);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("field","",249,277);
$z[4][4]['name']="typeurl";
$z[5]=Array("arclist","\r\n      <li class=\"\r\n[field:pubdate runphp='yes']  \r\n\$a=\"new\"; \r\n\$b=\"\";    \r\n\$c=strftime(\"%d\",\"@me\");\r\n\$d=date(d); \r\nif(\$c==\$d) @me = \$a;  \r\nelse @me = \$b;  \r\n[/field:pubdate]   \r\n   \">\r\n      <span class=\"date\">[field:pubdate runphp='yes']  \r\n      \$a=\"日\"; \r\n      \$b=\"今日\";    \r\n      \$c=strftime(\"%Y%m%d\",\"@me\");\r\n      \$d=date(Ymd); \r\n      \$e=strftime(\"%d\",\"@me\");\r\n      if(\$c==\$d) @me = \$b;  \r\n      else @me = \$e.\$a;  \r\n      [/field:pubdate]</span><span class=\"title\"><a title=\"[field:fulltitle/]\" target=\"_blank\" href=\"[field:global.cfg_basehost/][field:arcurl/]\">[field:shorttitle/]</a></span>\r\n      </li>\r\n      ",322,1002);
$z[5][4]['row']="12";
$z[5][4]['titlelen']="60";

?>