<?php
$z[0]=Array("fulltitle","",31,49);
$z[1]=Array("global","",73,101);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("arcurl","",101,116);
$z[3]=Array("global","",143,171);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("litpic","",171,186);
$z[5]=Array("fulltitle","",204,222);
$z[6]=Array("global","",246,274);
$z[6][4]['name']="cfg_basehost";
$z[7]=Array("arcurl","",274,289);
$z[8]=Array("shorttitle","",310,329);

?>