<?php
$z[0]=Array("pubdate","  \r\n\$a=\"new\"; \r\n\$b=\"\";    \r\n\$c=strftime(\"%d\",\"@me\");\r\n\$d=date(d); \r\nif(\$c==\$d) @me = \$a;  \r\nelse @me = \$b;  \r\n",13,167);
$z[0][4]['runphp']="yes";
$z[1]=Array("pubdate","  \r\n      \$a=\"Ше\"; \r\n      \$b=\"НёШе\";    \r\n      \$c=strftime(\"%Y%m%d\",\"@me\");\r\n      \$d=date(Ymd); \r\n      \$e=strftime(\"%d\",\"@me\");\r\n      if(\$c==\$d) @me = \$b;  \r\n      else @me = \$e.\$a;  \r\n      ",204,444);
$z[1][4]['runphp']="yes";
$z[2]=Array("fulltitle","",481,499);
$z[3]=Array("global","",523,551);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("arcurl","",551,566);
$z[5]=Array("shorttitle","",568,587);

?>