<?php
$z[0]=Array("fulltitle","",15,33);
$z[1]=Array("global","",57,85);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("arcurl","",85,101);
$z[3]=Array("shorttitle","",113,132);
$z[4]=Array("global","",162,190);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("litpic","",190,205);
$z[6]=Array("fulltitle","",261,279);
$z[7]=Array("global","",303,331);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("arcurl","",331,347);
$z[9]=Array("shorttitle","",357,376);
$z[10]=Array("info","",411,454);
$z[10][4]['function']="cn_substr(@me,108)";

?>