<?php
$z[0]=Array("global","",8,33);
$z[0][4]['name']="autoindex";
$z[1]=Array("global","",38,66);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("arcurl","",66,81);
$z[3]=Array("global","",92,117);
$z[3][4]['name']="autoindex";
$z[4]=Array("global","",123,151);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("litpic","",151,166);
$z[6]=Array("global","",178,203);
$z[6][4]['name']="autoindex";
$z[7]=Array("shorttitle","",208,227);

?>