<?php
$z[0]=Array("fulltitle","",14,32);
$z[1]=Array("arcurl","",56,71);
$z[2]=Array("shorttitle","",106,125);
$z[3]=Array("global","",157,185);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("litpic","",185,200);
$z[5]=Array("fulltitle","",265,283);
$z[6]=Array("arcurl","",307,322);
$z[7]=Array("shorttitle","",332,351);
$z[8]=Array("pubdate","",390,432);
$z[8][4]['function']="GetDateMK(@me)";
$z[9]=Array("description","",495,515);

?>