<div id="hd">
<div id="nav"><a title="X攻略网www.xueyi.cc提供最新教育培训机构行业综合资讯，各种培训计划、培训方案、培训总结、培训心得体会等专业内容，欢迎访问学艺网！" href="http://www.xueyi.cc/" class="logo"><img alt="学艺网,培训机构,培训计划,培训总结,培训方案,培训心得体会" height="28" width="140" src="http://www.xueyi.cc/style/images/logo.png" /></a>
<ul class="nav_list">
    <li><a title="学艺网www.xueyi.cc提供最新教育培训机构行业综合资讯，各种培训计划、培训方案、培训总结、培训心得体会等专业内容，欢迎访问学艺网！" href="http://www.xueyi.cc/" class="nav-item nav-item-2">首页</a></li>
</ul>
<div class="tb-item dm"><a href="http://www.xueyi.cc/news/" class="nav-item nav-item-2">业界动态</a></div>
<div class="tb-item dm"><a href="http://www.xueyi.cc/music/" class="nav-item nav-item-2">学音乐</a></div>
<div class="tb-item dm"><a href="http://www.xueyi.cc/dianshang/" class="nav-item nav-item-2">学电商</a></div>
<div class="tb-item dm"><a href="http://www.xueyi.cc/jineng/" class="nav-item nav-item-2">技艺技能</a></div>
<div class="tb-nav">
<div class="tb-item">
<div class="sc"></div>
</div>
<div class="tb-item"><a href="javascript:;" class="item-link item-link-5">阅读设置</a></div>
</div>
</div>
</div>