<li><a title="[field:fulltitle/]" target="_blank" href="[field:global.cfg_basehost/][field:arcurl/]" class="list_thumbnail"><img alt="[field:shorttitle/]" height="100" width="100" src="[field:global.cfg_basehost/][field:litpic/]"></a>
          <div class="block">
            <h2><a title="[field:fulltitle/]" target="_blank" href="[field:global.cfg_basehost/][field:arcurl/]"><strong>[field:shorttitle/]</strong></a><span class="state other">[field:pubdate function="GetDateMK(@me)"/]</span></h2>
            <div class="memo">
              <p>[field:description/]</p>
            </div>
            <span class="tags"><strong>Tags£º</strong></span></div>
        </li>