<?php
$z[0]=Array("fulltitle","",15,33);
$z[1]=Array("arcurl","",57,72);
$z[2]=Array("shorttitle","",84,103);
$z[3]=Array("global","",133,161);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("litpic","",161,176);
$z[5]=Array("fulltitle","",226,244);
$z[6]=Array("arcurl","",268,283);
$z[7]=Array("shorttitle","",285,304);
$z[8]=Array("pubdate","",342,389);
$z[8][4]['function']="MyDate('Y.m.d',@me)";

?>