<?php
$z[0]=Array("fulltitle","",15,33);
$z[1]=Array("global","",57,85);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("arcurl","",85,100);
$z[3]=Array("shorttitle","",112,131);
$z[4]=Array("global","",161,189);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("litpic","",189,204);
$z[6]=Array("fulltitle","",254,272);
$z[7]=Array("global","",296,324);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("arcurl","",324,339);
$z[9]=Array("shorttitle","",341,360);
$z[10]=Array("pubdate","",398,445);
$z[10][4]['function']="MyDate('Y.m.d',@me)";

?>