<li><a title="[field:fulltitle/]" target="_blank" href="[field:arcurl/]" class="list_thumbnail"><img alt="[field:shorttitle/]" height="100" width="100" src="[field:litpic/]"></a>
          <div class="block">
            <h2><a title="[field:fulltitle/]" target="_blank" href="[field:arcurl/]"><strong>[field:shorttitle/]</strong></a><span class="state other">[field:senddate function="GetDateMK(@me)"/]</span></h2>
            <div class="memo">
              <p>[field:description/]</p>
            </div>
            <span class="tags"><strong>Tags：</strong></span></div>
        </li>