<?php
$z[0]=Array("pubdate","  \r\n\$a=\"new\"; \r\n\$b=\"\";    \r\n\$c=strftime(\"%d\",\"@me\");\r\n\$d=date(d); \r\nif(\$c==\$d) @me = \$a;  \r\nelse @me = \$b;  \r\n",13,167);
$z[0][4]['runphp']="yes";
$z[1]=Array("pubdate","  \r\n            \$a=\"日\"; \r\n            \$b=\"今日\";    \r\n            \$c=strftime(\"%Y%m%d\",\"@me\");\r\n            \$d=date(Ymd); \r\n            \$e=strftime(\"%d\",\"@me\");\r\n            if(\$c==\$d) @me = \$b;  \r\n            else @me = \$e.\$a;  \r\n            ",210,501);
$z[1][4]['runphp']="yes";
$z[2]=Array("fulltitle","",538,556);
$z[3]=Array("arcurl","",580,595);
$z[4]=Array("shorttitle","",597,616);

?>